### ISSUE TITLE
Cannot find by vue cli service - This dependency was not found error

### ISSUE THREAD

**Issue by JacobFJ** [Vannsl/vue-3-sanitize#1]
I got this log after I declare it to main.js

`
vue-cli-service]  WAIT  Compiling...1:11:39 AM
[vue-cli-service] This dependency was not found:
[vue-cli-service] * vue-3-sanitize in ./src/main.js
[vue-cli-service] To install it, you can run: npm install --save vue-3-sanitize
[vue-cli-service]  WAIT  Compiling...1:12:21 AM
[vue-cli-service] This relative module was not found:
[vue-cli-service] * ../node_modules/vue-3-sanitize in ./src/main.js
`
I installed it using 
npm install --save vue-3-sanitize.

**Comment by JacobFJ** [comment]
#2 fix

**Comment by JacobFJ** [comment]
It will close after the author merge the pull request.

**Comment by Vannsl** [comment]
thanks!

**Comment by JacobFJ** [comment]
the request has been merge.. now we can close it now..
