### ISSUE TITLE
Cannot find module 'vue-3-sanitize' or its corresponding type declarations

### ISSUE THREAD

**Issue by iknowmagic** [Vannsl/vue-3-sanitize#3]
Hi Vanessa,

Thank you for making the vue-sanitize project available to Vue 3 :)

I am getting an error while trying to import the module into Vue 3 / Typescript:

`Cannot find module 'vue-3-sanitize' or its corresponding type declarations`

Thanks.

**Comment by binarykiwi** [comment]
Same with me:
```
Failed to resolve entry for package "vue-3-sanitize".
The package may have incorrect main/module/exports specified in its package.json.
```
Thanks a.lot for a fix and I will use it :)

**Comment by bjacob596** [comment]
I have this same issue as-well. 

`This dependency was not found: * 'vue-3-sanitize' in ...`

Thank you for this package, Is there any update on this? 

Thanking you in advance for a fix.

**Comment by manuel-ch** [comment]
same here

**Comment by mirekys** [comment]
I noticed the cause of this error is that the built package refers to the wrong dist file, it comes with:
```json
  "main": "dist/vue-sanitize.js",
```
but the dist file is actually named:
```
dist/vue-3-sanitize.js
```

**Comment by Vannsl** [comment]
Feel free to open a PR

**Comment by say8425** [comment]
> Could not find a declaration file for module 'vue-3-sanitize'.

~~I used 0.1.4 but this isssue is not solve yet on Vue3/TypeScript.~~

Nevermind.
I just create `vue-3-sanitize.d.ts` file and add `declare module "vue-3-sanitize";`.
